title: "maxulysse.github.io"
description: "Interested in Bioinformatics, Reproducible Research, Automation, Data Integration and Visualization..."
baseurl: ""
url: "https://maxulysse.github.io"
words_per_minute : 160

logo:
  path: "/assets/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

markdown: kramdown
highlighter: rouge

paginate: 6
permalink: pretty
theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
  style: compact

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

include:
  - "_pages"

exclude:
  - [vendor]
  - "LICENSE"
  - "README.md"
  - "assets/mycv/.*"
  - "assets/mycv/*.md"
  - "assets/mycv/*.tex"
  - "assets/mycv/*201*.pdf"
  - "assets/mycv/biblio.bib"
  - "assets/mycv/LICENSE"
  - "assets/mycv/pictures/"
  - "assets/mycv/scripts/"
  - "assets/courses/.*"
  - "assets/courses/*.md"
  - "assets/courses/*.tex"
  - "assets/courses/LICENSE"
  - "assets/courses/pictures/"
  - "assets/presentations/.*"
  - "assets/presentations/*.md"
  - "assets/presentations/*.tex"
  - "assets/presentations/LICENSE"
  - "assets/presentations/pictures/"
  - "assets/presentations/scripts/"
  - "scripts"
